name: Deploy to Combell

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper git operations

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.domain.be >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to Combell
        run: |
          # Replace with your actual Combell repository URL
          COMBELL_REPO="domainbe@ssh.domain.be:auto.git"

          # Add Combell as a remote and push
          git remote add combell $COMBELL_REPO
          git push combell main:master
